#ifndef VOXL_KEYBOARD_H
#define VOXL_KEYBOARD_H


namespace voxl {

// AZERTY
typedef enum AzertyScancode {
  SCANCODE_ESCAPE = 41,
  SCANCODE_TAB = 43,
  SCANCODE_CAPSLOCK = 57,
  SCANCODE_LSHIFT = 225,
  SCANCODE_RSHIFT = 229,
  SCANCODE_LCTRL = 224,
  SCANCODE_RCTRL = 228,
  SCANCODE_LALT = 226,
  SCANCODE_RALT_ALTGR = 230,
  SCANCODE_LGUI = 227,
  SCANCODE_RGUI = 231,
  SCANCODE_SPACE = 44,
  SCANCODE_RETURN = 40,
  SCANCODE_BACKSPACE = 42,

  SCANCODE_INSERT = 73,
  SCANCODE_DELETE = 76,
  SCANCODE_HOME = 74,
  SCANCODE_END = 77,
  SCANCODE_PAGEUP = 75,
  SCANCODE_PAGEDOWN = 78,
  SCANCODE_LEFT = 80,
  SCANCODE_RIGHT = 79,
  SCANCODE_UP = 82,
  SCANCODE_DOWN = 81,

  SCANCODE_F1 = 58,
  SCANCODE_F2 = 59,
  SCANCODE_F3 = 60,
  SCANCODE_F4 = 61,
  SCANCODE_F5 = 62,
  SCANCODE_F6 = 63,
  SCANCODE_F7 = 64,
  SCANCODE_F8 = 65,
  SCANCODE_F9 = 66,
  SCANCODE_F10 = 67,
  SCANCODE_F11 = 68,
  SCANCODE_F12 = 69,

  SCANCODE_SUPERSCRIPT2 = 53,

  SCANCODE_AMPERSAND = 30,
  SCANCODE_EACUTE = 31,
  SCANCODE_QUOTEDBL = 32,
  SCANCODE_APOSTROPHE_4 = 33,
  SCANCODE_LPAREN = 34,
  SCANCODE_MINUS_6 = 35,
  SCANCODE_EGRAVE = 36,
  SCANCODE_UNDERSCORE = 37,
  SCANCODE_CCEDILLA = 38,
  SCANCODE_AGRAVE = 39,

  SCANCODE_RPAREN = 45,
  SCANCODE_EQUALS = 46,

  SCANCODE_A = 20,
  SCANCODE_Z = 26,
  SCANCODE_E = 8,
  SCANCODE_R = 21,
  SCANCODE_T = 23,
  SCANCODE_Y = 28,
  SCANCODE_U = 24,
  SCANCODE_I = 12,
  SCANCODE_O = 18,
  SCANCODE_P = 19,

  SCANCODE_DIAERESIS_CARET = 47,
  SCANCODE_DOLLAR = 48,

  SCANCODE_Q = 4,
  SCANCODE_S = 22,
  SCANCODE_D = 7,
  SCANCODE_F = 9,
  SCANCODE_G = 10,
  SCANCODE_H = 11,
  SCANCODE_J = 13,
  SCANCODE_K = 14,
  SCANCODE_L = 15,

  SCANCODE_M = 51,
  SCANCODE_UGRAVE = 52,
  SCANCODE_ASTERISK = 49,

  SCANCODE_LESS_GREATER = 100,

  SCANCODE_W = 29,
  SCANCODE_X = 27,
  SCANCODE_C = 6,
  SCANCODE_V = 25,
  SCANCODE_B = 5,
  SCANCODE_N = 17,

  SCANCODE_COMMA = 16,
  SCANCODE_SEMICOLON = 54,
  SCANCODE_COLON = 55,
  SCANCODE_EXCLAMATION = 56,
} Scancode;


} // namespace voxl


#endif //! VOXL_KEYBOARD_H